(function(){
const V={drama:["Жить ярко, свободно выражать себя и чувствовать эмоциональный отклик других людей.","ярко проявляться и быть увиденной"],iron:["Чувствовать порядок, надёжность и самой управлять происходящим.","порядок и контроль"],great:["Добиться значимого результата и действительно что-то изменить.","большая цель и результат"],outsider:["Оставаться собой, думать по-своему и не подстраиваться под чужие правила.","внутренняя независимость"],hyper:["Чувствовать движение, свободу, новые впечатления и возможность изменить маршрут.","движение и свобода"],fairy:["Чувствовать настоящую близость, тепло и бережную связь с дорогими людьми.","тепло и близость"],turtle:["Чувствовать безопасность, спокойствие и отсутствие неприятных неожиданностей.","безопасность и устойчивость"],martyr:["Знать, что на тебе многое держится и без тебя другим было бы тяжелее.","долг и надёжность"]};
const SPEC={
"drama__iron":["Если невозможно сохранить и то и другое, что для тебя важнее?",V.drama[0],V.iron[0]],"drama__great":["Что для тебя важнее в глубине души?","Быть увиденной и услышанной, выражать себя и оставлять сильное впечатление.",V.great[0]],"drama__outsider":["Без чего твоя жизнь быстрее потеряет краски и смысл?","Без возможности открыто проявлять себя и получать живой отклик.","Без возможности оставаться собой и думать по-своему."],"drama__hyper":["Что для тебя важнее?","Ярко проявиться и почувствовать, что тебя заметили и запомнили.",V.hyper[0]],"drama__fairy":["Что для тебя ценнее?","Чувствовать, что тебя видят, слышат и принимают такой, какая ты есть.",V.fairy[0]],"drama__turtle":["Какое состояние для тебя важнее сохранить?","Возможность жить ярко и не прятать свои чувства.",V.turtle[0]],"drama__martyr":["Что даёт тебе более глубокое ощущение собственной ценности?",V.drama[0],V.martyr[0]],
"iron__great":["Что для тебя важнее?","Навести порядок, выстроить надёжную систему и держать происходящее под контролем.","Направить силы на большую цель и получить весомый результат."],"iron__outsider":["Без чего тебе было бы труднее оставаться собой?","Без ясных правил, порядка и понимания, что всё на своих местах.","Без права мыслить независимо и поступать по-своему."],"iron__hyper":["Какой образ жизни тебе внутренне ближе?","Когда всё организовано и происходящее можно контролировать.","Когда есть свобода действий, движение и минимум жёстких ограничений."],"iron__fairy":["Что для тебя важнее сохранить в сложной ситуации?","Порядок, справедливость и ясные договорённости.","Тепло и человеческую связь, даже если придётся уступить."],"iron__turtle":["Что сильнее даёт тебе ощущение безопасности?","Самой навести порядок, принять решение и взять всё под контроль.","Не торопиться, проверить риски и не делать шага без уверенности."],"iron__martyr":["Что для тебя важнее, когда на тебе многое держится?","Организовать всех и добиться, чтобы каждый выполнил свою часть.","Самой выдержать нагрузку и сделать необходимое."],
"great__outsider":["Какой результат для тебя ценнее?","Реализовать большую цель и увидеть весомый результат.","Создать что-то действительно своё, даже если не все это поймут."],"great__hyper":["Что для тебя важнее в жизни?","Выбрать большую цель и последовательно двигаться к ней.","Сохранять свободу движения и идти туда, где больше энергии."],"great__fairy":["Что даёт тебе более глубокое ощущение, что ты живёшь не зря?","Понимание, что ты реализовала важную идею и изменила что-то большее.","Понимание, что рядом с тобой людям стало теплее и легче."],"great__turtle":["Если приходится выбирать, что для тебя важнее?","Пойти к значимой цели, даже если придётся рискнуть.","Сохранить устойчивость и не подвергать себя непредсказуемому риску."],"great__martyr":["Что для тебя важнее в трудном деле?","Довести свою идею до результата и изменить существующий порядок.","Остаться верной долгу, даже если никто этого не замечает."],
"outsider__hyper":["Какая свобода для тебя важнее?","Свобода думать по-своему и не быть как все.","Свобода двигаться, менять планы и получать новые впечатления."],"outsider__fairy":["Что для тебя важнее сохранить?","Верность себе, даже если возникнет дистанция с людьми.","Тёплую связь с близкими, даже если придётся немного подстроиться."],"outsider__turtle":["Что для тебя важнее?","Жить в соответствии со своей логикой, независимо от чужих ожиданий.","Жить спокойно, предсказуемо и без лишнего риска."],"outsider__martyr":["Что для тебя важнее в глубине души?","Сохранить внутреннюю независимость и право не жить по чужим ожиданиям.","Выполнить долг и остаться человеком, на которого можно положиться."],
"hyper__fairy":["Что быстрее возвращает тебе ощущение настоящей жизни?","Движение, новые возможности и свобода делать интересное.","Тёплое общение, близость и люди, с которыми можно быть собой."],"hyper__turtle":["Какое состояние для тебя важнее?","Идти в новое и не знать заранее, куда приведёт следующий поворот.","Понимать последствия и не подвергать себя лишнему риску."],"hyper__martyr":["Если невозможно совместить оба варианта, что для тебя важнее?","Сохранить свободу и изменить то, что перестало приносить радость.","Остаться и выполнить обязательства, даже если это тяжело."],"fairy__turtle":["Что для тебя важнее в отношениях с людьми?","Сохранить близость и честно показать своё отношение.","Сохранить спокойствие и не открываться там, где есть риск отвержения."],"fairy__martyr":["Когда ты помогаешь близкому человеку, что для тебя важнее?","Чтобы между вами было тепло и хорошо было не только ему, но и тебе.","Сделать всё необходимое, даже если самой придётся потерпеть."],"turtle__martyr":["Что для тебя важнее в тяжёлой ситуации?","Сберечь себя и не брать последствий, с которыми трудно справиться.","Выдержать нагрузку и сделать то, что от тебя зависит."]};
const ORDER=data.profiles.map(p=>p.id);let tieState=null,resolvedRanking=null;const oldSave=save;
save=function(){oldSave();try{localStorage.setItem(STORAGE_KEY+"_tie",JSON.stringify({tieState,ids:resolvedRanking&&resolvedRanking.map(x=>x.profile.id)}))}catch{}};
function base(){let s=Object.fromEntries(ORDER.map(x=>[x,0])),p=Object.fromEntries(ORDER.map(x=>[x,0]));data.questions.forEach((q,i)=>{let c=choices[i],a=q.answers[c.primary],b=q.answers[c.secondary];s[a.type]+=2;p[a.type]++;s[b.type]++});return data.profiles.map(profile=>({profile,score:s[profile.id],primary:p[profile.id]})).sort((a,b)=>b.score-a.score||ORDER.indexOf(a.profile.id)-ORDER.indexOf(b.profile.id))}
function conflict(r){let a=r.filter(x=>x.score===r[0].score);if(a.length>1)return{fixed:[],group:a,slots:2};let b=r.filter(x=>x.score===r[1].score);return b.length>1?{fixed:[r[0]],group:b,slots:1}:null}
function key(a,b){return ORDER.indexOf(a)<ORDER.indexOf(b)?a+"__"+b:b+"__"+a}function pairs(ids){let z=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)z.push([ids[i],ids[j]]);return z}
function begin(){let r=base(),c=conflict(r);if(!c){resolvedRanking=r;screen="result";save();return renderResults()}tieState={fixed:c.fixed.map(x=>x.profile.id),group:c.group.map(x=>x.profile.id),slots:c.slots,pairs:pairs(c.group.map(x=>x.profile.id)),index:0,votes:{},selected:null};screen="tie";save();renderTie()}
function finish(){let r=base(),by=Object.fromEntries(r.map(x=>[x.profile.id,x])),win=tieState.group.slice().sort((a,b)=>(tieState.votes[b]||0)-(tieState.votes[a]||0)||by[b].primary-by[a].primary||ORDER.indexOf(a)-ORDER.indexOf(b)).slice(0,tieState.slots),front=tieState.fixed.concat(win);resolvedRanking=front.map(x=>by[x]).concat(r.filter(x=>!front.includes(x.profile.id)).sort((a,b)=>b.score-a.score||b.primary-a.primary||ORDER.indexOf(a.profile.id)-ORDER.indexOf(b.profile.id)));screen="result";save();renderResults()}
renderTie=function(){let pair=tieState.pairs[tieState.index],k=key(...pair),q=SPEC[k],ord=k.split("__"),txt={[ord[0]]:q[1],[ord[1]]:q[2]};app.className="tie-shell";app.innerHTML=`<section class="tie-card"><p class="eyebrow">Нужно уточнить результат</p><h1>Два психотипа набрали одинаковое количество баллов</h1><p class="lead">Выбери не то, что у тебя чаще получается, а то, что для тебя важнее внутри. Представь, что невозможно сохранить оба варианта и нужно выбрать только один.</p>${tieState.pairs.length>1?`<p class="tie-progress">Сравнение ${tieState.index+1} из ${tieState.pairs.length}</p>`:""}<p class="tie-question">${esc(q[0])}</p><div class="tie-options">${pair.map(id=>`<button class="tie-option" data-tie="${id}" aria-pressed="${tieState.selected===id}">${esc(txt[id])}</button>`).join("")}</div><button class="button primary tie-next" data-action="tie-next" ${tieState.selected?"":"disabled"}>${tieState.index===tieState.pairs.length-1?"Увидеть результат":"Далее"}</button></section>`;document.querySelectorAll("[data-tie]").forEach(b=>b.onclick=()=>{tieState.selected=b.dataset.tie;save();renderTie()});bindAction("tie-next",()=>{if(!tieState.selected)return;tieState.votes[tieState.selected]=(tieState.votes[tieState.selected]||0)+1;tieState.index++;tieState.selected=null;tieState.index<tieState.pairs.length?(save(),renderTie()):finish()})};
const oldRender=render;render=function(){if(screen==="tie"&&complete()&&tieState)return renderTie();return oldRender()};
nextQuestion=function(){let c=choices[questionIndex];if(!c||c.primary===null||c.secondary===null||c.primary===c.secondary)return;if(questionIndex<19){questionIndex++;save();render();scrollTo(0,0);return}let bad=choices.findIndex(x=>!x||x.primary===null||x.secondary===null||x.primary===x.secondary);if(bad>=0){questionIndex=bad;save();render();return}resolvedRanking=null;tieState=null;begin();scrollTo(0,0)};
function combo(r){let open=false;return `<section class="combination-section"><div class="combination-inner"><p class="eyebrow">Твоя персональная интерпретация</p><h2>${esc(r.title)}</h2>${r.blocks.map(b=>{if(b.type==="h2"||b.type==="h3"){let x=(open?"</section>":"")+`<section class="combination-block"><h3>${esc(b.text)}</h3>`;open=true;return x}if(b.type==="p")return `<p>${esc(b.text)}</p>`;if(b.type==="list")return `<ul>${b.items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;if(b.type==="table")return `<div class="responsive-table"><table>${b.rows.map((row,i)=>`<tr>${row.map(c=>i?`<td>${esc(c)}</td>`:`<th>${esc(c)}</th>`).join("")}</tr>`).join("")}</table></div>`;return""}).join("")}${open?"</section>":""}</div></section>`}
renderResults=function(){let rnk=resolvedRanking||base(),a=rnk[0],b=rnk[1],r=PERSONAL_RESULTS[a.profile.id+"__"+b.profile.id];app.className="results";app.innerHTML=`${rankingTable(rnk)}${meaningBlock()}${position([a],"1 место — твоё естество")}${position([b],"2 место — твоя стратегия")}${combo(r)}<section class="download-stack"><article class="download-card"><p class="eyebrow">Персональный файл</p><h2>Твой результат</h2><p>Только твоё сочетание: ${esc(r.title)}. Без описаний других психотипов.</p><div class="download-actions"><a class="button light" href="${r.pdf}" target="_blank">Открыть PDF</a><a class="button light" href="${r.pdf}" download>Скачать PDF</a></div></article><article class="download-card general"><p class="eyebrow">Полный справочник</p><h2>Описание всех психотипов</h2><p>Материал обо всех восьми психотипах.</p><div class="download-actions"><a class="button light" href="psychotypes_A4.pdf" target="_blank">Открыть PDF</a><a class="button light" href="psychotypes_A4.pdf" download>Скачать PDF</a></div></article></section><footer><p>${esc(data.disclaimer)}</p><button class="button secondary" data-action="restart">Пройти тест заново</button></footer>`;bindAction("restart",()=>{if(confirm("Начать тест заново? Текущий результат будет сброшен.")){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(STORAGE_KEY+"_tie");tieState=null;resolvedRanking=null;choices=data.questions.map(()=>({primary:null,secondary:null}));questionIndex=0;go("instructions")}})};
try{let x=JSON.parse(localStorage.getItem(STORAGE_KEY+"_tie"));if(x){tieState=x.tieState;if(x.ids){let by=Object.fromEntries(base().map(y=>[y.profile.id,y]));resolvedRanking=x.ids.map(id=>by[id]).filter(Boolean)}}}catch{}
function pdfUrl(r){if(r._url)return r._url;let s=atob(r.pdfData),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return r._url=URL.createObjectURL(new Blob([a],{type:"application/pdf"}))}
const renderWithPdf=renderResults;renderResults=function(){renderWithPdf();let rnk=resolvedRanking||base(),r=PERSONAL_RESULTS[rnk[0].profile.id+"__"+rnk[1].profile.id],links=document.querySelectorAll(".download-card:first-child a");links.forEach((a,i)=>{a.href=pdfUrl(r);if(i===1)a.download=r.title+".pdf"})}
if(tieState&&!resolvedRanking){screen="tie";renderTie()}else if(resolvedRanking&&complete()){screen="result";renderResults()}
})();
